### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by bengalspice** [sharpastralena/sql-scratch-capstone-turn-in#1]
Report: 4/4
Questions were answered with supporting data, but I would have liked to have seen some elaboration on the learner's analysis.

Query Accuracy: 4/4
All quires correctly retrieved intended data.

Query Formatting:  4/4
Followed Style Guide for SQL 

Understanding underlying concepts and terminology:  2/4
While terms were used correctly throughout the presentation, it wasn't clear whether the learner really understood what the parameters meant.

Overall: 14/16
I would have liked to have seen more analysis and elaboration done.  The responses to the questions was way too concise. 

Otherwise, Great Job!

**Comment by sharpastralena** [comment]
Thanks!
